// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Ww4lVSevwE03vnBQD_6a1dE8q_hEB7I',
    appId: '1:952856924555:web:16bfea16024d410ca51f8e',
    messagingSenderId: '952856924555',
    projectId: 'new180-8ca1f',
    authDomain: 'new180-8ca1f.firebaseapp.com',
    storageBucket: 'new180-8ca1f.firebasestorage.app',
    measurementId: 'G-Z6ML9D8Y6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhC9aGFkVAtHz6eMKVzB1jfuJCSv1QKH0',
    appId: '1:952856924555:android:099b89b2ec009a48a51f8e',
    messagingSenderId: '952856924555',
    projectId: 'new180-8ca1f',
    storageBucket: 'new180-8ca1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJHpFiXxq4FopZ4slofvi7b9w1bGoJ0W8',
    appId: '1:952856924555:ios:35e06a4f5cf68afaa51f8e',
    messagingSenderId: '952856924555',
    projectId: 'new180-8ca1f',
    storageBucket: 'new180-8ca1f.firebasestorage.app',
    iosBundleId: 'com.example.hlw1',
  );
}
